#!/bin/bash

g++ -o godot/2d/bridge.os \
-c \
-fno-gnu-unique \
-std=c++17 \
-fno-exceptions \
-fPIC \
-Wwrite-strings \
-m64 \
-march=x86-64 \
-fvisibility=hidden \
-O2 \
-DLINUX_ENABLED -DUNIX_ENABLED -DTHREADS_ENABLED -DHOT_RELOAD_ENABLED -DDEBUG_ENABLED -DNDEBUG -DGDEXTENSION \
-Igodot-cpp/include -Igodot-cpp/gen/include -Iinclude \
godot/2d/bridge.cpp

g++ -o bin/libCPPTEMPLATE.so \
-Wl,-R,'$ORIGIN' \
-m64 \
-march=x86-64 \
-static-libgcc \
-static-libstdc++ \
-fvisibility=hidden \
-s \
-shared \
godot/2d/bridge.os \
godot-cpp/bin/libgodot-cpp.linux.template_debug.x86_64.a
